log4rs_config: "/var/repos/oxIDIZER/conf/log4rs.yaml"

modules:
  - id: messaging_mqtt
    name: ox_messaging_mqtt
    path: "/var/repos/oxIDIZER/target/debug/libox_messaging_mqtt.so"
    broker_port: 3001
    config_file: "/var/repos/oxIDIZER/ox_messaging_client/ox_messaging_mqtt/functional_tests/000001-ConfigInvalid/conf/bad_broker.yaml"

servers:
  - id: "default_http"
    protocol: "http"
    port: 3000
    bind_address: "0.0.0.0"
    hosts:
      - name: "localhost"

pipeline:
  phases:
    - Content: "ox_pipeline_router"
