pub mod state;

use parking_lot::RwLock;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::ffi::{c_char, CString};
use std::sync::Arc;
use indexmap::IndexSet;
use uuid::Uuid;

use crate::state::TaskState;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TaskStatus {
    Queued,
    Running,
    Paused,
    Errored,
    Completed,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HistoryRecord {
    pub stage_name: String,
    pub plugin_name: Option<String>,
    pub status: String,
    pub message: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskFlags {
    pub stage: IndexSet<String>,
    pub persistent: IndexSet<String>,
}

impl TaskFlags {
    pub fn new() -> Self {
        Self {
            stage: IndexSet::new(),
            persistent: IndexSet::new(),
        }
    }
}

/// The core task object that is passed around and orchestrated.
pub struct Task {
    pub id: Uuid,
    pub priority: u32,
    pub status: TaskStatus,
    /// Memory is entirely owned by this RwLock and instantiated once during flow start.
    pub state: Arc<RwLock<TaskState>>,
    /// Metadata visible to engine but separate from the plugin state
    pub metadata: HashMap<String, String>,
    /// Ephemeral flags
    pub flags: TaskFlags,
    /// Child workflows forked from this task via FFI insert_into_flow
    pub child_workflows: Vec<String>,
    /// Execution history entries generated during plugin runs, batched for storage
    pub history: Vec<HistoryRecord>,
    /// Error callback optionally set when an error occurs
    pub error_callback: Option<Box<dyn Fn() + Send + Sync>>,
    /// Arena to securely drop CString pointers generated by FFI get_* calls
    pub ffi_arena: Vec<*mut c_char>,
    /// Per-function call counts for rate limiting (function name → count)
    pub api_call_counts: HashMap<String, u32>,
    /// Per-function call limits (function name → max, 0 = unlimited)
    pub api_limits: HashMap<String, u32>,
}

impl Drop for Task {
    fn drop(&mut self) {
        for ptr in self.ffi_arena.drain(..) {
            if !ptr.is_null() {
                unsafe { let _ = CString::from_raw(ptr); }
            }
        }
    }
}

unsafe impl Send for Task {}
unsafe impl Sync for Task {}

impl Task {
    pub fn new(priority: u32) -> Self {
        Self {
            id: Uuid::new_v4(),
            priority,
            status: TaskStatus::Queued,
            state: Arc::new(RwLock::new(TaskState::new())),
            metadata: HashMap::new(),
            flags: TaskFlags::new(),
            child_workflows: Vec::new(),
            history: Vec::new(),
            error_callback: None,
            ffi_arena: Vec::new(),
            api_call_counts: HashMap::new(),
            api_limits: HashMap::new(),
        }
    }
}

/// A stage specifies a runner and an ordered list of plugins
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct StageDef {
    pub name: String,
    pub runner: String,
    pub plugins: Vec<PluginDef>,
    pub on_error: Option<String>,
}

/// Config for a specific plugin library in a stage
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct PluginDef {
    pub name: String,
    pub config: Option<serde_json::Value>,
}

/// Flow definitions compose an execution path of multiple stages
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct FlowDef {
    pub name: String,
    pub persistent: bool,
    pub stages: Vec<String>,
}
