log4rs_config: "/var/repos/oxIDIZER/conf/log4rs.yaml"

modules:
  - id: ping_module
    name: ox_webservice_ping
    path: "/var/repos/oxIDIZER/target/debug/libox_webservice_ping.so"
  - id: ox_pipeline_router
    name: ox_pipeline_router
    path: "/var/repos/oxIDIZER/target/debug/libox_pipeline_router.so"

servers:
  - id: "default_http"
    protocol: "http"
    port: 3000
    bind_address: "0.0.0.0"
    hosts:
      - name: "localhost"

pipeline:
  phases:
    - Content: "ox_pipeline_router"

routes:
  - url: "^/ping"
    module_id: "ping_module"
    phase: Content
    priority: 100
