pipeline:
  phases:
    - Content: "ox_pipeline_router"

modules:
  - id: "ping_module"
    name: "ox_webservice_ping"
    path: "/var/repos/oxIDIZER/target/debug/libox_webservice_ping.so"

  - id: "data_source_manager_skip"
    name: "ox_persistence_datasource_manager"
    path: "/var/repos/oxIDIZER/target/debug/libox_persistence_datasource_manager.so"
    params:
      data_sources_dir: "/var/repos/oxIDIZER/ox_persistence_datasource_manager/functional_tests/200002-ConflictManagement/conf/datastores"
      on_content_conflict: "skip"

  - id: "data_source_manager_error"
    name: "ox_persistence_datasource_manager"
    path: "/var/repos/oxIDIZER/target/debug/libox_persistence_datasource_manager.so"
    params:
      data_sources_dir: "/var/repos/oxIDIZER/ox_persistence_datasource_manager/functional_tests/200002-ConflictManagement/conf/datastores"
      on_content_conflict: "error"

  - id: "ox_pipeline_router"
    name: "ox_pipeline_router"
    path: "/var/repos/oxIDIZER/target/debug/libox_pipeline_router.so"
    params:
      routes:
        # Route 1: Ping module handles /ping
        - matcher:
            path: "^/ping$"
          module_id: "ping_module"
          priority: 100
        
        # Route 2: Conflict skip (matches /ping too)
        - matcher:
            path: "^/ping$"
          module_id: "data_source_manager_skip"
          priority: 200

        # Route 3: /conflict_error
        - matcher:
            path: "^/conflict_error$"
          module_id: "ping_module"
          priority: 100
        - matcher:
            path: "^/conflict_error$"
          module_id: "data_source_manager_error"
          priority: 200

servers:
  - id: "default"
    protocol: "http"
    port: %BASE_PORT%
    bind_address: "127.0.0.1"

log4rs_config: "/var/repos/oxIDIZER/ox_persistence_datasource_manager/functional_tests/200002-ConflictManagement/conf/log4rs.yaml"
