pipeline:
  # ----------------------------------------------------------------------------
  # Pipeline Phases
  # ----------------------------------------------------------------------------
  # The execution order of request processing phases.
  # Modules are assigned to specific phases to perform their tasks.
  # FlowControl signals from modules determine transition between these phases.
  phases:
    - PreEarlyRequest: "ox_pipeline_router"
    - EarlyRequest: "ox_pipeline_router"
    - PostEarlyRequest: "ox_pipeline_router"
    - PreAuthentication: "ox_pipeline_router"
    - Authentication: "ox_pipeline_router"
    - PostAuthentication: "ox_pipeline_router"
    - PreAuthorization: "ox_pipeline_router"
    - Authorization: "ox_pipeline_router"
    - PostAuthorization: "ox_pipeline_router"
    - PreContent: "ox_pipeline_router"
    - Content: "ox_pipeline_router"
    - PostContent: "ox_pipeline_router"
    - PreAccounting: "ox_pipeline_router"
    - Accounting: "ox_pipeline_router"
    - PostAccounting: "ox_pipeline_router"
    - PreErrorHandling: "ox_pipeline_router"
    - ErrorHandling: "ox_pipeline_router"
    - PostErrorHandling: "ox_pipeline_router"
    - PreLateRequest: "ox_pipeline_router"
    - LateRequest: "ox_pipeline_router"
    - PostLateRequest: "ox_pipeline_router"
