#!/usr/bin/env bash
# install-ca-cert.sh
#
# Installs a CA certificate that was signed by an external root CA in response
# to a CSR generated by generate-root-ca.sh --csr-only.
#
# Verifies the signed certificate matches the locally generated key, confirms
# it carries CA:true, copies it into place, updates the web download directory,
# and optionally adds the issuing chain to the system trust store.
#
# Usage:
#   sudo ./scripts/install-ca-cert.sh <signed-cert.pem> [OPTIONS]
#
# Options:
#   --chain <file>       PEM file containing the issuing CA chain (root + any intermediates)
#   --content-dir <dir>  Override the web content directory for root.crt download
#   --no-trust           Skip adding the issuing chain to the system trust store
#   --start              Start ox_webservice after installation
#   --help               Show this help message

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
SIGNED_CERT=""
CHAIN_FILE=""
ADD_TRUST=true
START_SERVICE=false
CONTENT_DIR_OVERRIDE=""

# ---------------------------------------------------------------------------
# OS-specific paths
# ---------------------------------------------------------------------------
detect_os() {
    case "$(uname -s)" in
        Linux*)             echo "linux"   ;;
        Darwin*)            echo "macos"   ;;
        MINGW*|MSYS*|CYGWIN*) echo "windows" ;;
        *)                  echo "unknown" ;;
    esac
}
OS=$(detect_os)

case "$OS" in
    linux)
        KEY_DIR="/etc/pki/ox_webservice/private"
        CA_DIR="/etc/pki/ox_webservice/ca"
        ;;
    macos)
        KEY_DIR="/etc/ssl/ox_webservice/private"
        CA_DIR="/etc/ssl/ox_webservice/ca"
        ;;
    windows)
        KEY_DIR="C:/ProgramData/ox_webservice/private"
        CA_DIR="C:/ProgramData/ox_webservice/ca"
        ;;
    *)
        echo "ERROR: Unsupported OS: $(uname -s)" >&2; exit 1 ;;
esac

ROOT_KEY="$KEY_DIR/default/ca-root.key.pem"
ROOT_CERT="$CA_DIR/root.crt"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
CONTENT_CA_DIR="$REPO_DIR/crates/cert/ox_cert_admin/content/www/ca"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
info()  { echo "  [INFO]  $*"; }
ok()    { echo "  [OK]    $*"; }
warn()  { echo "  [WARN]  $*"; }
fatal() { echo "  [ERROR] $*" >&2; exit 1; }

check_root() {
    if [[ "$OS" != "windows" && "$EUID" -ne 0 ]]; then
        fatal "This script must be run as root (sudo ./scripts/install-ca-cert.sh ...)"
    fi
}

require_cmd() {
    command -v "$1" &>/dev/null || fatal "'$1' is required but not installed."
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
if [[ $# -eq 0 ]]; then
    sed -n '/^# Usage/,/^[^#]/p' "$0" | grep '^#' | sed 's/^# \?//'
    exit 1
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        --chain)        CHAIN_FILE="$2";            shift 2 ;;
        --content-dir)  CONTENT_DIR_OVERRIDE="$2";  shift 2 ;;
        --no-trust)     ADD_TRUST=false;             shift   ;;
        --start)        START_SERVICE=true;          shift   ;;
        --help)
            sed -n '/^# Usage/,/^[^#]/p' "$0" | grep '^#' | sed 's/^# \?//'
            exit 0
            ;;
        -*)  fatal "Unknown option: $1" ;;
        *)
            if [[ -z "$SIGNED_CERT" ]]; then
                SIGNED_CERT="$1"; shift
            else
                fatal "Unexpected argument: $1"
            fi
            ;;
    esac
done

[[ -n "$CONTENT_DIR_OVERRIDE" ]] && CONTENT_CA_DIR="$CONTENT_DIR_OVERRIDE"

# ---------------------------------------------------------------------------
echo
echo "ox Certificate Authority — Signed Certificate Installer"
echo "========================================================"
echo

check_root
require_cmd openssl

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
[[ -z "$SIGNED_CERT" ]]   && fatal "No signed certificate file specified."
[[ ! -f "$SIGNED_CERT" ]] && fatal "Signed certificate not found: $SIGNED_CERT"
[[ ! -f "$ROOT_KEY" ]]    && fatal "CA private key not found at $ROOT_KEY — run generate-root-ca.sh --csr-only first."

info "Checking signed certificate..."
openssl x509 -in "$SIGNED_CERT" -noout 2>/dev/null \
    || fatal "Not a valid PEM certificate: $SIGNED_CERT"

# Verify the cert's public key matches our private key.
# The root CA key file is always unencrypted on disk; OX_CA_KEY_PASS is for the
# keystore only and must NOT be passed to openssl pkey for the PEM key file.
info "Verifying certificate matches private key..."
CERT_PUBKEY=""
if ! CERT_PUBKEY="$(openssl x509 -in "$SIGNED_CERT" -noout -pubkey 2>&1)"; then
    echo "  [ERROR] Could not extract public key from certificate: ${CERT_PUBKEY}"
    exit 1
fi
[[ -n "$CERT_PUBKEY" ]] || { echo "  [ERROR] Empty public key from certificate."; exit 1; }

KEY_PUBKEY=""
if ! KEY_PUBKEY="$(openssl pkey -in "$ROOT_KEY" -pubout 2>&1)"; then
    echo "  [ERROR] Could not read public key from ${ROOT_KEY}: ${KEY_PUBKEY}"
    exit 1
fi
[[ -n "$KEY_PUBKEY" ]] || { echo "  [ERROR] Empty public key from ${ROOT_KEY}."; exit 1; }

if [[ "$CERT_PUBKEY" != "$KEY_PUBKEY" ]]; then
    echo "  [ERROR] Public key mismatch — cert was not signed for key at ${ROOT_KEY}"
    exit 1
fi
ok "Key match verified."

# Verify CA:true
info "Verifying CA certificate constraints..."
CA_FLAG=$(openssl x509 -in "$SIGNED_CERT" -noout -text 2>/dev/null | grep -c "CA:TRUE" || true)
[[ "$CA_FLAG" -gt 0 ]] \
    || fatal "Certificate does not have CA:TRUE in basicConstraints — not a valid CA certificate."

KEY_USAGE=$(openssl x509 -in "$SIGNED_CERT" -noout -text 2>/dev/null \
    | grep -A2 "Key Usage" | grep -c "Certificate Sign" || true)
[[ "$KEY_USAGE" -gt 0 ]] \
    || warn "Key Usage does not include Certificate Sign — verify the signing CA included correct extensions."
ok "CA constraints verified."

# ---------------------------------------------------------------------------
# Install signed certificate
# ---------------------------------------------------------------------------
info "Installing signed certificate..."
mkdir -p "$CA_DIR"
cp "$SIGNED_CERT" "$ROOT_CERT"
chmod 444 "$ROOT_CERT"
chown root:root "$ROOT_CERT" 2>/dev/null || true
ok "Installed: $ROOT_CERT"

# ---------------------------------------------------------------------------
# Handle issuing chain
# ---------------------------------------------------------------------------
if [[ -n "$CHAIN_FILE" ]]; then
    [[ ! -f "$CHAIN_FILE" ]] && fatal "Chain file not found: $CHAIN_FILE"
    openssl crl2pkcs7 -nocrl -certfile "$CHAIN_FILE" -out /dev/null 2>/dev/null \
        || openssl x509 -in "$CHAIN_FILE" -noout 2>/dev/null \
        || fatal "Not a valid PEM file: $CHAIN_FILE"

    info "Installing issuing chain..."
    cp "$CHAIN_FILE" "$CA_DIR/chain.pem"
    chmod 444 "$CA_DIR/chain.pem"
    ok "Chain installed: $CA_DIR/chain.pem"

    if [[ "$ADD_TRUST" == true ]]; then
        info "Adding issuing chain to system trust store..."
        case "$OS" in
            linux)
                if command -v update-ca-certificates &>/dev/null; then
                    cp "$CHAIN_FILE" /usr/local/share/ca-certificates/ox-issuing-ca.crt
                    update-ca-certificates
                    ok "Trusted (Debian/Ubuntu)."
                elif command -v update-ca-trust &>/dev/null; then
                    cp "$CHAIN_FILE" /etc/pki/ca-trust/source/anchors/ox-issuing-ca.crt
                    update-ca-trust extract
                    ok "Trusted (RHEL/Fedora)."
                else
                    warn "Cannot detect trust mechanism — add $CHAIN_FILE to your system trust store manually."
                fi
                ;;
            macos)
                security add-trusted-cert -d -r trustRoot \
                    -k /Library/Keychains/System.keychain "$CHAIN_FILE"
                ok "Trusted (macOS System Keychain)."
                ;;
            *)
                warn "Add $CHAIN_FILE to your system trust store manually."
                ;;
        esac
    fi
fi

# ---------------------------------------------------------------------------
# Copy certificate to web content directory for download
# ---------------------------------------------------------------------------
info "Copying certificate to web content directory..."
mkdir -p "$CONTENT_CA_DIR"
cp "$ROOT_CERT" "$CONTENT_CA_DIR/root.crt"
ok "Web download ready: $CONTENT_CA_DIR/root.crt"

# ---------------------------------------------------------------------------
# Display certificate details
# ---------------------------------------------------------------------------
echo
echo "Certificate details:"
openssl x509 -in "$ROOT_CERT" -noout \
    -subject -issuer -dates \
    -fingerprint -sha256 \
    | sed 's/^/  /'
echo

# ---------------------------------------------------------------------------
# Start service
# ---------------------------------------------------------------------------
if [[ "$START_SERVICE" == true ]]; then
    if [[ -d /run/systemd/system ]]; then
        info "Starting ox_webservice..."
        systemctl start ox_webservice.service
        ok "ox_webservice started."
    else
        warn "--start specified but systemd not detected; start the service manually."
    fi
else
    echo "─────────────────────────────────────────────────────────────"
    echo " Certificate installed successfully."
    echo
    echo " Start the service with:"
    echo "   sudo systemctl start ox_webservice"
    echo "─────────────────────────────────────────────────────────────"
    echo
fi
